version: 2
jobs:
  build:
    docker:
      - image: dbosk/makefiles
    steps:
      - checkout
      - run: git submodule update --init
      - run: LATEXFLAGS="-interaction=nonstopmode -use-make" make all
      - run: git submodule deinit
